

services: 
  arexx2hass:
    image: zdid2/arexx2hass:${VERSION}
    container_name: arexx2hass
    privileged: true
    build: 
      context: .
      platforms:
        - "linux/x86"
        - "linux/amd64"
        - "linux/arm64" 
        - "linux/arm"
    volumes:
      - ../config:/app/data
    environment:
      AREXX2HASS_MQTT_SERVER: localhost
      TZ: Europe/Paris
    restart: unless-stopped 
    #devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0

