loglevel: info
homeassistant:
  discovery: true
  base_topic: arexx2hass
  discovery_bridge_unique_id: ArexxBridge_000001
  topics:
    discovery: homeassistant/device/%discovery_bridge_unique_id%/%device_unique_id%/config
    command: "%base_topic%/%discovery_bridge_unique_id%/%device_unique_id%/%command\
      type%"
    state: "%base_topic%/%discovery_bridge_unique_id%/%device_unique_id%/state"
    will: "%base_topic%/%discovery_bridge_unique_id%/status"
    homeassistant_availability: homeassistant/status
    ecoute: "%base_topic%/%discovery_bridge_unique_id%/#"
mqtt:
  base_topic: arexx2hass
  homeassistant_enable_discovery: true
  server: ftp://localhost:1883
  username: null
  password: null
  qos: 0
  retain: false
  retain_config: true
arexx:
  #address: null
  port_dist: 80
  httpserv_port: 49161
  isusb: false
  
